#!/bin/bash
# Restore Script for Mechanics of Machine Lab

# Restore Script restores the backup of the data used by the lab.
# Since there is no data being used by Mechanics of Machine Lab, 
# the script does nothing. 

# Usage of the script

# To use restore script, run the command
# ./scripts/restore
